### ISSUE TITLE
MusicPlayer2 edits tag incorrectly...

### ISSUE THREAD

**Issue by IPeluchito** [zhongyang219/MusicPlayer2#631]
https://github.com/zhongyang219/MusicPlayer2/assets/64821708/5117bea7-a35c-4549-8b76-43abce0e7ec9

**Comment by IPeluchito** [comment]
Fixed !!! but now how do I delete what has been duplicated? ..... Is it possible that MusicPlayer2 can edit advanced tags?

**Comment by lrisora** [comment]
> Fixed !!! but now how do I delete what has been duplicated? ..... Is it possible that MusicPlayer2 can edit advanced tags?

Most likely Musicplayer2 will not support direct editing of advanced tags. I use another software [Mp3tag](https://www.mp3tag.de/en/) to edit tags.
Because there are so many potential entries for advanced tags (see Mp3tag), 
it may not be necessary to implement full functionality.
However, it is not impossible within the scope of TagLib support.

![圖片](https://github.com/zhongyang219/MusicPlayer2/assets/43085437/4a88d51f-0df6-4c77-8960-2adc8ab5bcf5)

**Comment by IPeluchito** [comment]
Ok, I understand...one last question, I would like to translate MusicPlayer2 to Spanish...how can I do it?

**Comment by lrisora** [comment]
MusicPlayer2 currently maintains a resource file for each language (the default solution provided by MFC). Adding new languages in this way is huge and difficult to maintain.
I think we should refactor first to extract all the strings that need to be translated, but the dynamic layout of MFC is very weak. Using unified resources will make it difficult to maintain the previous compact layout effect (such as the Chinese option setting window).

@zhongyang219 计划大概如下（还在考虑中，没问题的话就慢慢改了
- `String Table`从ini加载（将英文做成`ui1.xml`那样内嵌）
- 窗口资源只留一份英文（其中字符串改长一些），在所有窗口初始化时设置显示字符串为当前语言的显示内容。
- 菜单资源不保留直接在程序启动时构建又或者留一份再用`ModifyMenuW`洗掉全部。
（助记键如何实现还在考虑，我不希望硬编码到翻译中，重复会有运行时异常）。

`IDR_TEXT1`怎样处理还没想好，放进ini感觉太长
窗口布局会大改，需要给字符串留出足够空间（控件不多的窗口可以写代码让控件重新适应文字大小）

**Comment by IPeluchito** [comment]
Ok, I will be waiting for that modification to translate MusicPlayer2 to spanish....

Thank you very much !!!
